erp5_wendelin: Remove alternate format testing as Python3 removes tuple-list comparison
BTrees (like OLBTree from Zope/BTrees package) use keys that must be comparable with <

because they are internally stored in a sorted structure.

but in python3, it raise error when compare tuple and list

TypeError: '<' not supported between instances of 'tuple' and 'list'