erp5_wendelin_data_lake_ingestion: We can't compare str with byte in Python3
  File "erp5://portal_components/test.erp5.testDataLakeIngestion", line 84, in ingestRequest
    encoded_data_chunk = base64.b64encode(data_chunk)
  File "/srv/slapgrid/slappart6/t/ewn/shared/python3/82d1b87c38e7fa7d56bbaba68e7b58a8/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'