erp5_wendelin_inventory: port to python3
1. map() function returns a map object in Python 3, we need list
  return np.dtype({
    'names': names,
    'formats': map(np.dtype, dtypes)
  })
  why raise error
    return np.dtype({
  ValueError: 'names', 'formats', 'offsets', and 'titles' dict entries must have the same length

 2. No more unicode in Python 3
  six.string_types is:
    (str, unicode) in Python 2
    (str,) in Python 3

 3. ix is deprecated

 4. numpy is more stricted for comparing structured or np.void elements to strings

  Traceback (most recent call last):
   File "erp5://portal_components/test.erp5.testPandasInventory", line 177, in test_03_importCategoryInformationTest
     self.assertTrue(all([item != '' for item in resource_category_array]))
   File "erp5://portal_components/test.erp5.testPandasInventory", line 177, in <listcomp>
     self.assertTrue(all([item != '' for item in resource_category_array]))
   TypeError: Cannot compare structured or void to non-void arrays.