erp5_wendelin/DataBucketStream: Hide buckets from Folder API to fix reindexing
Before this patch, reindexing the 'data_stream' module containing
'Data Bucket Stream' was broken [1]. The failure occurred because the
reindexing logic attempted to recursively process 'Data Bucket Stream',
which contains 'PersistentString' objects.

These 'PersistentString' buckets are not acquisition-based objects,
which caused the inherited Folder.iteritems method to break. Even if
they were acquisition objects, indexing them would still be problematic -
these buckets are large, not intended to be cataloged, and don't need to
be searchable.

The root cause is that the buckets were accessible via the Folder API.
This led to issues in the past, such as a bug with the consistency check
on 'Data Bucket Stream' [2]. To address the problem at its source,
this patch updates the schema of 'Data Bucket Stream' to make the
buckets inaccessible through the Folder API. This is a safe change
because 'Data Bucket Stream' already provides its own API to iterate
over or retrieve buckets.

The schema migration is performed automatically when updating Wendelin
with this patch. Once all relevant instances have been updated, we
should consider dropping the __setstate__ compatibility code.

---

[1] ActivityTool Could not call method recursiveReindexObject on object ('', 'erp5', 'data_stream_module'). Activity created at:
  File "/srv/slapgrid/slappart18/srv/runner/shared/python2.7/f5675c59f3468f8b18752cbd67ef1b7d/lib/python2.7/threading.py", line 774, in __bootstrap
    self.__bootstrap_inner()
  File "/srv/slapgrid/slappart18/srv/runner/shared/python2.7/f5675c59f3468f8b18752cbd67ef1b7d/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/srv/slapgrid/slappart18/srv/runner/shared/python2.7/f5675c59f3468f8b18752cbd67ef1b7d/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/waitress-1.4.4-py2.7.egg/waitress/task.py", line 86, in handler_thread
    task.service()
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/waitress-1.4.4-py2.7.egg/waitress/channel.py", line 350, in service
    task.service()
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/waitress-1.4.4-py2.7.egg/waitress/task.py", line 171, in service
    self.execute()
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/waitress-1.4.4-py2.7.egg/waitress/task.py", line 441, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/waitress-1.4.4-py2.7.egg/waitress/proxy_headers.py", line 65, in translate_proxy_headers
    return app(environ, start_response)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5/bin/zopewsgi.py", line 62, in __call__
    return self.application(environ, replacement_start_response)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5/bin/zopewsgi.py", line 147, in app
    return publish_module(environ, start_response)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/patches/WSGIPublisherZope2.py", line 465, in publish_module
    response = _publish(request, new_mod_info)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/patches/WSGIPublisherZope2.py", line 398, in publish
    bind=1)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/Zope2-2.13.30-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/Zope2-2.13.30-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s<cr> to step into published object.
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/patches/PythonScript.py", line 182, in __call__
    return self._orig_bindAndExec(args, kw, None)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/Zope2-2.13.30-py2.7.egg/Shared/DC/Scripts/Bindings.py", line 359, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/Products.PythonScripts-2.13.2-py2.7.egg/Products/PythonScripts/PythonScript.py", line 344, in _exec
    result = f(*args, **kw)
  File "Script (Python)", line 92, in ERP5Site_reindexAll
    after_tag=(user_tag, category_tag, preference_tag),
  File "Script (Python)", line 31, in reindex
    sql_catalog_id=sql_catalog_id,
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/CMFActivity/ActivityTool.py", line 564, in __call__
    portal_activities=portal_activities,
Traceback (most recent call last):
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/CMFActivity/ActivityTool.py", line 366, in __call__
    result = method(*self.args, **self.kw)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/Core/Folder.py", line 1355, in recursiveReindexObject
    skip_method_id='_isDocumentNonIndexable',
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/Core/Folder.py", line 618, in _recurseCallMethod
    recurse(self, 0)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/Core/Folder.py", line 604, in recurse
    recurse(ob, depth + 1)
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/Core/Folder.py", line 601, in recurse
    for id, ob in container.iteritems(next_id):
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/eggs/AccessControl-2.13.16-py2.7-linux-x86_64.egg/AccessControl/ZopeGuards.py", line 205, in next
    return self._next()
  File "/srv/slapgrid/slappart18/srv/runner/software/e79f05ea40fb656eb775d6c909e3d4eb/parts/erp5/product/ERP5Type/Core/Folder.py", line 1129, in <genexpr>
    return NullIter(((x, y.__of__(self)) for x, y in result))
AttributeError: 'PersistentString' object has no attribute '__of__'

[2] https://lab.nexedi.com/nexedi/wendelin/-/commit/72b3dc973f9d33f8599fe243bba85b35c51de687

/reviewed-on https://lab.nexedi.com/nexedi/wendelin/-/merge_requests/171
/reviewed-by @Tyagov, @klaus and @paul.graydon