erp5_wendelin_drone: we can't compare str with byte in Python3
   - <PyData Script at /erp5_portal_2dc6e7beea9d202c5b944f9d33d1d5c0/DataAnalysisLine_recalculateScore used for /erp5_portal_2dc6e7beea9d202c5b944f9d33d1d5c0/data_analysis_module/03072025-03072025-03072025-20250703-drone_simulation-convert_drone_raw_data-create_score_list_array-recalculate_score_list_array/1>
   - Line 73
    if len([x for x in sim_flight_names if x not in seen_sims]) == 0:
TypeError: 'in <string>' requires string as left operand, not bytes